os.loadAPI("/UtilsAPI")
-- Variables

local isRunning = true
-- local version = "0.1"  Not used anymore

-- End of Variables



-- Functions
function setColors(color1, color2)
  if term.isColor() then
   
  term.setBackgroundColor(color1)
  term.setTextColor(color2)
  else
  
  end
end


function exit()
term.setBackgroundColor(colors.black)
term.setTextColor(colors.white)
term.clear()
term.setCursorPos(1,1)
print("Thanks for using TajamSoft software!")
sleep(1)
term.setCursorPos(1,1)
term.clear()
os.unloadAPI("/UtilsAPI")

end
function startupLock()
term.setCursorPos(1,1)
setColors(colors.blue, colors.white)
term.clear()
UtilsAPI.centerPrint(" |Create a startup lock| ", 2)
UtilsAPI.centerPrint(" ----------------------- ", 3)
term.setCursorPos(4,6)
setColors(colors.white, colors.black)
write("Password: ")
local newPassword = read()
local writePassword = newPassword
setColors(colors.blue, colors.white)

term.setCursorPos(4,8)
print(" Ready to create passworld lock")
print(" If a startup exists this will backup it")
sleep(2)
if fs.exists("/startup-backupTjs") then
   print(" Deleted old backup...")
   fs.delete("/startup-backupTjs")
end
if fs.exists("/startup") then
 fs.copy("/startup", "/startup-backupTjs")
  print("Created backup of startup file...")
  sleep(0.5)
end    
sleep(0.5)
local nst = fs.open("/startup","w")
nst.writeLine("-- This file is generated by TajamSoft PassCreator")
nst.writeLine('local password = "'..writePassword..'"')
nst.writeLine('local pullEvent = os.pullEvent')
nst.writeLine('os.pullEvent = os.pullEventRaw')
nst.writeLine('while true do')
nst.writeLine('term.clear()')
nst.writeLine('term.setCursorPos(1,1)')
nst.writeLine('write("Password: ")')
nst.writeLine('local input = read("*")')
nst.writeLine('if input == password then')
nst.writeLine('term.clear()')
nst.writeLine('term.setCursorPos(1,1)')
nst.writeLine('print("Correct!!")')
nst.writeLine('os.pullEvent = pullEvent')
nst.writeLine('break')
nst.writeLine('else')
nst.writeLine('print("Password is not correct!!")')
nst.writeLine('end')
nst.writeLine('end')
nst.writeLine('-- end of generated file --')
nst.close()
sleep(2)
print(" File is generated!")
print(" The password is: "..writePassword)
print(" Reboot in 3 seconds...")
os.unloadAPI("/utilsAPI")
sleep(3)
os.reboot()
end

function doorLock()


end

function help()
term.setCursorPos(1,1)
term.clear()
term.setCursorPos(1,1)
setColors(colors.blue, colors.white)
term.clear()
UtilsAPI.centerPrint(" Help: ",2)
UtilsAPI.centerPrint("-------------------------------------",3)
print(" Create a statup lock:")
print("  This will lock the computer whit a password")
print("  The user needs to write the password when the computer starts")
print(" Create a door lock:")
print("  This will create a door lock")
print("  The lock may run at startup or when the program itself is runned")
print(" Force Update:")
print("  This will redownload the program")
print("---------------------------------------------")
print("Press any key to continue...")
if os.pullEvent(key) then
  mainMenu()
end
end

function update()


end

function waitSelection()
  term.setCursorPos(15,9)
  term.write("Selection: ")
  local select = read() 
  if select == "1" then
    startupLock()
  elseif select == "2" then
    doorLock()
  elseif select == "4" then
    help()
  elseif select == "3" then
    update()
  else
    exit()
  end

end


function mainMenu()
setColors(colors.blue, colors.white)
term.clear()
UtilsAPI.centerPrint(" Press Enter to exit ",2)
UtilsAPI.centerPrint("Welcome to TajamSoft PassWord Lock",3)
UtilsAPI.centerPrint("What do you want to do? : ",4)
UtilsAPI.centerPrint("1) Startup Password Lock",5)
UtilsAPI.centerPrint("2) Door PassWord Lock",6)
UtilsAPI.centerPrint("3) Force Update",7)
UtilsAPI.centerPrint("4) Help",8)


term.setCursorPos(12,9)
setColors(colors.white, colors.black)
print("                             ")
waitSelection()
end
-- End of functions


-- Program
mainMenu()

-- End of program

